version: '2.4'
services:
  backend:
    image: gridgain/gridgain-web-console-backend:2019.12.02
    # Restart on crash.
    restart: always
    environment:
      # Mail settings
      #- SPRING_MAIL_HOST=
      #- SPRING_MAIL_PORT=
      #- SPRING_MAIL_USERNAME=
      #- SPRING_MAIL_PASSWORD=
      - JVM_OPTS=

    volumes:
      - ${PWD}/work:/opt/gridgain-web-console-server/work

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/swagger-ui.html"]
      interval: 5s # interval health check
      timeout: 2s # timeout for check
      retries: 10 # maximum retries

  frontend:
    image: gridgain/gridgain-web-console-frontend:2019.12.02
    depends_on:
      backend:
        condition: service_healthy
    ports:
      # Proxy HTTP nginx port (HOST_PORT:DOCKER_PORT)
      - 80:8008